### ISSUE TITLE
Error on Initial Page

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata-team.github.io#3]
Hi, 

I believe there is an error in the Inicial page:

![Pasted image](https://github.com/plugdata-team/plugdata-team.github.io/assets/31707161/760d701f-e17b-4ebc-8f5a-a2e5116fcc35)

Is this gif in the right place?

**Comment by dromer** [comment]
Which browser are you using? In FF it looks correct for me:

![](https://i.imgur.com/MLnWQkj.png)

[edit: looking more closely I guess you have a previous version, please check if this is still the case]

**Comment by charlesneimog** [comment]
I think it was a previous version....
